### ISSUE TITLE
about the file refs(unc).p

### ISSUE THREAD

**Issue by 201528014227051** [shengyuzhang/DeVLBert#2]
thanks for sharing the codes. 
When I try to run the refcoco+ task, It raises “No such file or directory”
'.../refcoco+/refcoco+/refs(unc).p'

Could u tell me where I can find the file, please?

Thak u very much.

**Comment by jiangtann** [comment]
The file path is at https://github.com/jiasenlu/vilbert_beta/blob/master/vlbert_tasks.yml#L76
You can refer to https://github.com/jiasenlu/vilbert_beta/tree/master/data to download all the data. We are completely consistent with vilbert.

**Comment by 201528014227051** [comment]
thanks
